// Services
import { getCityByStateUf } from "../../../../../services/externalApisService"

export const initialInfoFields = [
  {
    name: "occupation",
    type: "text",
    placeholder: "Cargo",
    label: "Cargo",
    required: true,
  },
  {
    name: "company",
    type: "text",
    label: "Empresa",
    placeholder: "Empresa",
    required: true,
  },
  {
    name: "employmentType",
    type: "select",
    options: [
      { value: "fullTime", label: "Tempo integral" },
      { value: "partTime", label: "Meio período" },
      { value: "autonomous", label: "Autônomo" },
      { value: "internship", label: "Estágio" },
      { value: "freelancer", label: "Freelancer" },
      { value: "temporary", label: "Temporário" },
      { value: "trainee", label: "Trainee" },
      { value: "apprentice", label: "Aprendiz" },
      { value: "volunteer", label: "Voluntário" },
      { value: "outsourced", label: "Terceirizado" },
    ],
    label: "Tipo de emprego",
    placeholder: "Selecione",
    required: true,
  },
  {
    name: "contractType",
    type: "select",
    options: [
      { value: "clt", label: "CLT" },
      { value: "pj", label: "PJ" },
      { value: "internship", label: "Contato de estágio" },
      { value: "other", label: "Outro" },
    ],
    label: "Tipo de contrato",
    placeholder: "Selecione",
    required: true,
  },
  {
    name: "typeLocation",
    type: "select",
    options: [
      { value: "remote", label: "Remoto" },
      { value: "onsite", label: "Presencial" },
      { value: "hybrid", label: "Híbrido" },
    ],
    label: "Tipo de localização",
    placeholder: "Selecione",
    required: true,
  },
  {
    name: "stateUf",
    type: "select",
    options: [
      { value: "AC", label: "Acre" },
      { value: "AL", label: "Alagoas" },
      { value: "AP", label: "Amapá" },
      { value: "AM", label: "Amazonas" },
      { value: "BA", label: "Bahia" },
      { value: "CE", label: "Ceará" },
      { value: "DF", label: "Distrito Federal" },
      { value: "ES", label: "Espírito Santo" },
      { value: "GO", label: "Goiás" },
      { value: "MA", label: "Maranhão" },
      { value: "MT", label: "Mato Grosso" },
      { value: "MS", label: "Mato Grosso do Sul" },
      { value: "MG", label: "Minas Gerais" },
      { value: "PA", label: "Pará" },
      { value: "PB", label: "Paraíba" },
      { value: "PR", label: "Paraná" },
      { value: "PE", label: "Pernambuco" },
      { value: "PI", label: "Piauí" },
      { value: "RJ", label: "Rio de Janeiro" },
      { value: "RN", label: "Rio Grande do Norte" },
      { value: "RS", label: "Rio Grande do Sul" },
      { value: "RO", label: "Rondônia" },
      { value: "RR", label: "Roraima" },
      { value: "SC", label: "Santa Catarina" },
      { value: "SP", label: "São Paulo" },
      { value: "SE", label: "Sergipe" },
      { value: "TO", label: "Tocantins" },
    ],
    label: "Localização - UF",
    ariaLabel: "UF",
    placeholder: "Selecione",
    required: false,
    dependentFor: "city",
    renderConditions: [
      {
        params: ["typeLocation"],
        expression: "return params[0] === 'onsite' || params[0] === 'hybrid'",
      },
    ],
  },
  {
    name: "city",
    type: "select",
    options: [],
    label: "Localização - Cidade",
    ariaLabel: "Cidade",
    placeholder: "Selecione",
    required: false,
    dependentOn: "stateUf",
    getOptions: getCityByStateUf,
    route:
      "https://servicodados.ibge.gov.br/api/v1/localidades/estados/paramValue/municipios",
    renderConditions: [
      {
        params: ["typeLocation", "stateUf"],
        expression:
          "return (params[0] === 'onsite' || params[0] === 'hybrid') && params[1] !== ''",
      },
    ],
  },
]
