import { getCityByStateUf } from "../../../../services/externalApisService"

export const basicInfoFields = [
  {
    type: "text",
    name: "name",
    placeholder: "John Doe",
    label: "Nome",
    required: true,
  },
  {
    name: "headline",
    type: "text",
    label: "Headline",
    maxLength: 120,
    placeholder: "Escreva uma breve frase que destaca as principais qualidades",
    required: false,
  },
  {
    name: "stateUf",
    type: "select",
    options: [
      { value: "AC", label: "Acre" },
      { value: "AL", label: "Alagoas" },
      { value: "AP", label: "Amapá" },
      { value: "AM", label: "Amazonas" },
      { value: "BA", label: "Bahia" },
      { value: "CE", label: "Ceará" },
      { value: "DF", label: "Distrito Federal" },
      { value: "ES", label: "Espírito Santo" },
      { value: "GO", label: "Goiás" },
      { value: "MA", label: "Maranhão" },
      { value: "MT", label: "Mato Grosso" },
      { value: "MS", label: "Mato Grosso do Sul" },
      { value: "MG", label: "Minas Gerais" },
      { value: "PA", label: "Pará" },
      { value: "PB", label: "Paraíba" },
      { value: "PR", label: "Paraná" },
      { value: "PE", label: "Pernambuco" },
      { value: "PI", label: "Piauí" },
      { value: "RJ", label: "Rio de Janeiro" },
      { value: "RN", label: "Rio Grande do Norte" },
      { value: "RS", label: "Rio Grande do Sul" },
      { value: "RO", label: "Rondônia" },
      { value: "RR", label: "Roraima" },
      { value: "SC", label: "Santa Catarina" },
      { value: "SP", label: "São Paulo" },
      { value: "SE", label: "Sergipe" },
      { value: "TO", label: "Tocantins" },
    ],
    label: "Localização - UF",
    ariaLabel: "UF",
    placeholder: "Selecione",
    dependencyFor: ["city"],
    required: false,
  },
  {
    name: "city",
    type: "select",
    options: [],
    label: "Localização - Cidade",
    ariaLabel: "Cidade",
    placeholder: "Selecione",
    required: false,
    dependentOn: "stateUf",
    getOptions: getCityByStateUf,
    route:
      "https://servicodados.ibge.gov.br/api/v1/localidades/estados/paramValue/municipios",
  },
]

export const sendMessageFields = [
  {
    name: "newMessage",
    type: "textarea",
    hasLabel: true,
    label: "Mensagem",
    placeholder: "Escreva uma mensagem para iniciar uma conversa",
    required: true,
  },
]
