// Services
import { getCityByStateUf } from "../../../services/externalApisService"

export const authFields = [
  {
    type: "text",
    name: "name",
    placeholder: "John Doe",
    label: "Nome",
    required: true,
  },
  {
    name: "email",
    type: "email",
    label: "E-mail",
    placeholder: "john.doe@example.com",
    regex: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
    regexErrorMessage: "Formato de e-mail inválido",
    required: true,
  },
  {
    name: "password",
    type: "password",
    label: "Senha",
    placeholder: "*****",
    required: true,
  },
]

export const aboutFields = [
  {
    type: "select",
    options: [
      {
        value: "tecnologia_informacao",
        label: "Tecnologia da Informação",
      },
      { value: "saude_medicina", label: "Saúde e Medicina" },
      { value: "educacao", label: "Educação" },
      { value: "varejo", label: "Varejo" },
      { value: "servicos_financeiros", label: "Serviços Financeiros" },
      { value: "manufatura", label: "Manufatura" },
      { value: "alimentacao_bebidas", label: "Alimentação e Bebidas" },
    ],
    name: "occupationArea",
    placeholder: "Selecione",
    label: "Setor de atuação",
    ariaLabel: "Setor de atuação",
    required: true,
  },
  {
    name: "stateUf",
    type: "select",
    options: [
      { value: "AC", label: "Acre" },
      { value: "AL", label: "Alagoas" },
      { value: "AP", label: "Amapá" },
      { value: "AM", label: "Amazonas" },
      { value: "BA", label: "Bahia" },
      { value: "CE", label: "Ceará" },
      { value: "DF", label: "Distrito Federal" },
      { value: "ES", label: "Espírito Santo" },
      { value: "GO", label: "Goiás" },
      { value: "MA", label: "Maranhão" },
      { value: "MT", label: "Mato Grosso" },
      { value: "MS", label: "Mato Grosso do Sul" },
      { value: "MG", label: "Minas Gerais" },
      { value: "PA", label: "Pará" },
      { value: "PB", label: "Paraíba" },
      { value: "PR", label: "Paraná" },
      { value: "PE", label: "Pernambuco" },
      { value: "PI", label: "Piauí" },
      { value: "RJ", label: "Rio de Janeiro" },
      { value: "RN", label: "Rio Grande do Norte" },
      { value: "RS", label: "Rio Grande do Sul" },
      { value: "RO", label: "Rondônia" },
      { value: "RR", label: "Roraima" },
      { value: "SC", label: "Santa Catarina" },
      { value: "SP", label: "São Paulo" },
      { value: "SE", label: "Sergipe" },
      { value: "TO", label: "Tocantins" },
    ],
    label: "Localização - UF",
    ariaLabel: "UF",
    placeholder: "Selecione",
    dependencyFor: ["city"],
    required: true,
  },
  {
    name: "city",
    type: "select",
    options: [],
    label: "Localização - Cidade",
    ariaLabel: "Cidade",
    placeholder: "Selecione",
    required: true,
    dependentOn: "stateUf",
    getOptions: getCityByStateUf,
    route:
      "https://servicodados.ibge.gov.br/api/v1/localidades/estados/paramValue/municipios",
  },
  {
    name: "website",
    type: "text",
    label: "Site",
    placeholder: "www.example.com",
  },
  {
    name: "companyType",
    type: "select",
    label: "Tipo de empresa",
    ariaLabel: "Tipo de empresa",
    options: [
      { value: "private", label: "Privada" },
      { value: "public", label: "Pública" },
    ],
    placeholder: "Selecione o tipo de empresa",
    required: true,
  },
]
